---
- name: Create ansible root user credential
  tower_credential:
    name: ansible-root
    organization: Default
    state: present
    kind: ssh
    ssh_key_data: "{{ github_deploy_key }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"


- name: Create ansible github user credential
  tower_credential:
    name: ansible-github
    organization: Default
    state: present
    kind: scm
    ssh_key_data: "{{ github_deploy_key }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"


- name: Create ansible vault credential
  tower_credential:
    name: ansible-vault
    organization: Default
    state: present
    kind: vault
    vault_id: ansible-vault
    vault_password: "{{ vault_awx_vault_password }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
