---
- name: Create Tower credentials
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    kind: "{{ item.kind }}"
    ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
    vault_id: "{{ item.vault_id | default(omit) }}"
    vault_password: "{{ item.vault_password | default(omit) }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ tower_credentials }}"
  when:
    - tower_credentials is defined
    - tower_credentials != None
