---
- name: Install Build Packages
  package:
    name: "{{ build_pkgs }}"
    state: present

- import_tasks: install-debian.yml
  when: ansible_os_family == "Debian"

#- import_tasks: install-redhat.yml
#  when: ansible_os_family == "RedHat"
