---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include_tasks:
    file: install.yml
    apply:
      tags:
        - project
  tags:
    - project

- include_tasks:
    file: configure.yml
    apply:
      tags:
        - project
  tags:
    - projectimport
    - projectclone
    - project