---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: install.yml

- import_tasks: configure.yml

- import_tasks: credentials.yml

- import_tasks: projects.yml

- import_tasks: inventories.yml

- import_tasks: jobs.yml
