---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include_tasks:
    file: install.yml
    apply:
      tags:
        - project
  tags:
    - project


- include_tasks:
    file: configure.yml
    apply:
      tags:
        - project
        - projectsettings
  tags:
    - project
    - projectsettings

- include_tasks:
    file: projects.yml
    apply:
      tags:
        - project
        - projectprojects
  tags:
    - project
    - projectprojects

- include_tasks:
    file: credentials.yml
    apply:
      tags:
        - project
        - projectcredentials
  tags:
    - project
    - projectcredentials

- include_tasks:
    file: inventories.yml
    apply:
      tags:
        - project
        - projectinventories
  tags:
    - project
    - projectinventories

- include_tasks:
    file: jobs.yml
    apply:
      tags:
        - project
        - projectjobs
  tags:
    - project
    - projectjobs