---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- import_tasks:
    file: install.yml
  tags:
    - project

- import_tasks:
    file: configure.yml
  tags:
    - project
    - projectsettings

- import_tasks:
    file: credentials.yml
  tags:
    - project
    - projectcredentials
    - projectjobs
    - projectprojects

- import_tasks:
    file: projects.yml
  tags:
    - project
    - projectjobs
    - projectprojects

- import_tasks:
    file: inventories.yml
  tags:
    - project
    - projectinventories

- import_tasks:
    file: jobs.yml
  tags:
    - project
    - projectjobs
